<?php
/**
 * 2007-2016 PrestaShop
 *
 * thirty bees is an extension to the PrestaShop e-commerce software developed by PrestaShop SA
 * Copyright (C) 2017 thirty bees
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    thirty bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017 thirty bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark & property of PrestaShop SA
 */
use TbUpdaterModule\UpgraderTools;

/** @var TbUpdater $this */
$channel = UpgraderTools::getConfig('channel');
?>

<div id="upgradeButtonBlock" class="panel col-lg-12">
	<div class="panel-heading"><i class="icon icon-wrench"></i> <?php echo $this->l('Start your Upgrade'); ?></div>
    <div class="blockOneClickUpgrade">
		<strong><?php echo $this->l('Your current thirty bees version'); ?>:</strong>
		<code><?php echo _TB_VERSION_; ?></code>
	</div>

    <?php if ($this->configOk()) : ?>
        <?php echo $this->display('tbupdater', 'views/templates/admin/channelselect.tpl'); ?>
        <?php if ($this->configOk()) : ?>
			<p class="clearfix configOk">
				<a href="" id="upgradeNow" class="upgradestep btn btn-primary btn-lg">
					<i class="icon icon-wrench"></i> <?php echo $this->l('Update thirty bees'); ?>
				</a>
			</p>
        <?php endif; ?>
	<?php else: ?>
		<strong><?php echo $this->l('Make sure every item on the checklist is OK before you continue'); ?></strong>
    <?php endif; ?>
</div>
