<?php
/**
 * Copyright (C) 2017-2019 thirty bees
 * Copyright (C) 2007-2016 PrestaShop SA
 *
 * thirty bees is an extension to the PrestaShop software by PrestaShop SA.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@thirtybees.com so we can send you a copy immediately.
 *
 * @author    thirty bees <modules@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2017-2019 thirty bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   Academic Free License (AFL 3.0)
 * PrestaShop is an internationally registered trademark of PrestaShop SA.
 */

use TbUpdaterModule\UpgraderTools;

/** @var TbUpdater $this */
$tokenPreferences = Tools::getAdminTokenLite('AdminPreferences');
// relative admin dir
$adminDir = trim(str_replace(_PS_ROOT_DIR_, '', _PS_ADMIN_DIR_), DIRECTORY_SEPARATOR);
$installVersion = ' 1.0.1';
$ajaxProcessor = \TbUpdaterModule\AjaxProcessor::getInstance();
?>
<script src="https://cdn.jsdelivr.net/sweetalert2/6.5.3/sweetalert2.min.js" integrity="sha256-mxvrozpI8ZhaD7mKlr0z1BLafn8YoTTJFobEo9wlCUM=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.5.3/sweetalert2.min.css" integrity="sha256-n3wlJfrvYrUl1vS7mEs17EWYDW8fpE6DQv95+EnpHoY=" crossorigin="anonymous">

<script type="text/javascript">
	window.tbupdater = {};
	window.tbupdater.manualMode = false;
	window.tbupdater._PS_MODE_DEV_ = <?php echo (defined('_PS_DEV_MODE_') && _PS_DEV_MODE_) ? 'true' : 'false'; ?>;
	window.tbupdater.PS_AUTOUP_BACKUP = <?php echo (UpgraderTools::getConfig(UpgraderTools::BACKUP)) ? 'true' : 'false' ?>;

    window.tbupdater.txtInProgress = '<?php echo $this->l('An update is currently in progress... Click "{OK}" to abort.'); ?>';

	window.tbupdater.firstTimeParams = <?php echo $ajaxProcessor->buildAjaxResult(); ?>;

    window.tbupdater.upgradeTabFileExists = <?php echo (file_exists(_PS_ADMIN_DIR_.DIRECTORY_SEPARATOR.'autoupgrade'.DIRECTORY_SEPARATOR.'ajax-upgradetab.php')) ? 'true' : 'false'; ?>;
    window.tbupdater.ajaxLocation = '<?php echo __PS_BASE_URI__.$adminDir.'/autoupgrade/ajax-upgradetab.php'; ?>';

    window.tbupdater.dir = '<?php echo $adminDir; ?>';
    window.tbupdater.token = '<?php echo Tools::getAdminTokenLite('AdminModules'); ?>';
    window.tbupdater.tab = '<?php echo get_class($this); ?>';

    window.tbupdater.channel = '<?php echo UpgraderTools::getConfig('channel'); ?>';

    window.tbupdater.currentIndex = '<?php echo $this->baseUrl; ?>';
    window.tbupdater.ajaxToken = '<?php echo $this->generateAjaxToken(); ?>';

  window.tbupdater.textVersionUpToDate = '<?php echo $this->l('Your thirty bees installation is up to date!'); ?>';
</script>
